version: '3.1'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    env_file:
      - ./application-env.properties
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
      MONGO_INITDB_DATABASE: your_database
    env_file:
      - ./application-env.properties
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    env_file:
      - ./application-env.properties
    container_name: redis_container
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro

  user-query-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/user-query-service/target/user-query-service.jar"
    ports:
      - "8093:8080"

  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/authentication-service/target/authentication-service.jar"
    ports:
      - "8081:8080"

  authorization-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/authorization-service/target/authorization-service.jar"
    ports:
      - "8082:8080"

  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/config-service/target/config-service.jar"
    ports:
      - "8083:8080"

  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/discovery-service/target/discovery-service.jar"
    ports:
      - "8084:8080"

  file-storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/file-storage-service/target/file-storage-service.jar"
    ports:
      - "8085:8080"

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/gateway-service/target/gateway-service.jar"
    ports:
      - "8086:8080"

  inventory-command-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/inventory-command-service/target/inventory-command-service.jar"
    ports:
      - "8087:8080"

  inventory-query-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/inventory-query-service/target/inventory-query-service.jar"
    ports:
      - "8088:8080"

#  notification-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: "java -jar /app/notification-service/target/notification-service.jar"
#    ports:
#      - "8089:8080"

  order-command-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/order-command-service/target/order-command-service.jar"
    ports:
      - "8090:8080"

  order-query-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/order-query-service/target/order-query-service.jar"
    ports:
      - "8091:8080"

  user-command-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: "java -jar /app/user-command-service/target/user-command-service.jar"
    ports:
      - "8092:8080"


volumes:
  mysql_data:
  mongo_data:
  redis_data:

