server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:
spring:
  application:
    name: authorization-service
  config:
    import: optional:configserver:http://localhost:8888/,optional:file:./application-env.properties

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost