server:
  port: 8084

spring:
  application:
    name: file-storage-service
  config:
    import: optional:configserver:http://localhost:8888/,optional:file:./application-env.properties
  data:
    mongodb:
      uri: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@localhost:27020/file)storage_db?authSource=admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
