server:
  port: 8080

spring:
  application:
      name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        # TODO - Adding all service (register, login etc)..
      - id: authentication-service
        uri: lb://authentication-service
        predicates:
          - Path=/auth/**

      - id: user-query-service
        uri: lb://user-query-service
        predicates:
          - Path=/users/login/**