server:
  port: 8081


spring:
  main:
    web-application-type: reactive
  application:
    name: authentication-service
    cloud:
      config:
        enabled: true
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        server:
          wait-time-in-ms-when-sync-empty: 0
      instance:
        hostname: localhost

jwt:
  secret: 171e5aaea357e45c60c669e04143cd580cb8e6dfda7c9f5394d3bb850ba3214d
  expiration: 2592000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
