server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:
spring:
  main:
    web-application-type: servlet
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://localhost:8888/,optional:file:./application-env.properties

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION_TIME}