spring:
  application:
    name: order-command-service
  config:
    import: optional:configserver:http://localhost:8888/,optional:file:./application-env.properties

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

