server:
  port: 8083

spring:
  application:
    name: order-command-service
  config:
    import: optional:configserver:http://localhost:8888/,optional:file:./application-env.properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3307/mck_orders?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
  sql:
    init:
      mode: never
      schema-locations: classpath:data.sql




logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate=DEBUG:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


