server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Borovaneca/config-server.git
          clone-on-start: true

eureka:
  instance:
    hostname: localhost
